### ISSUE TITLE
如何配合Tasker控制全局开关？

### ISSUE THREAD

**Issue by Typhonling** [WuDi-ZhanShen/ScreenOff#2]
能否添加全局开关快捷方式？或者shell命令控制。
参考https://github.com/Xposed-Modules-Repo/me.neversleep.plusplus

**Comment by WuDi-ZhanShen** [comment]
请在酷安搜索息屏运行dex版，这就是你要的命令行工具

**Comment by Typhonling** [comment]
> 在酷安没找到呢 能否再给个途径呢

https://meta.appinn.net/t/topic/46361
